---
- name: Set en_US to locale.gen
  ansible.builtin.copy:
    src: locale.gen
    dest: /etc/locale.gen
    mode: "0644"
  notify: Generate locales

# - name: Ensure localisation files are available for '{{ base_config_locale }}'
#   community.general.locale_gen:
#     name: "{{ base_config_locale }}"
#     state: present
#
# - name: Get current locale configuration
#   ansible.builtin.command: localectl status
#   register: locale_status
#   changed_when: false
#
# - name: Parse 'LANG' from curent locale conrfiguration
#   ansible.builtin.set_fact:
#     locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"
#
# - name: Parse 'LANGUAGE' from current locale configuration
#   ansible.builtin.set_fact:
#     locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"
#
# - name: Configure locale to '{{ base_config_locale }}'
#   ansible.builtin.command: localectl set-locale LANG={{ base_config_locale }} LANGUAGE={{ base_config_locale }}
#   changed_when: locale_lang != base_config_locale or locale_language != base_config_locale
