---
- name: Set timezone to Europe/Berlin
  community.general.timezone:
    name: Europe/Berlin

- name: Disable systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: stopped
    enabled: false

- name: Remove systemd-timesyncd package
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: absent

- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Remove all default chrony pools
  ansible.builtin.replace:
    path: /etc/chrony/chrony.conf
    regexp: '^pool.*$'
    replace: ''
    backup: true

- name: Add Cloudflare NTP server
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    line: 'server time.cloudflare.com minpoll 4 maxpoll 8 polltarget 32 iburst'
    insertbefore: BOF
  notify: Restart chronyd
