---
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Generate locales
  ansible.builtin.shell:
    cmd: locale-gen
  changed_when: false
